#include <stdio.h>
int main(void)

{

	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" * P R O G R A M M I N G 1 *\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("C                           E\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  O                       N\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("    M                   S\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("      P               E\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("        5           5\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("          0       0\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("            0   1\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("              *\n");

	return 0;

}