#include <stdio.h>

int main(void)
{
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("    /\\     /\\	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("   //\\\\___//\\\\	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  /           \\	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" /   _     _   \\	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("/   (o)   (o)   \\	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|       Y       |	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("\\ ====|_|_|==== /	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" \\             /	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  \\-----------/	 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("   ---(P%%1)---		 \n");
printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" //-----------\\\\	 \n");
	return 0;
}