#include <stdio.h>
int main(void)

{

	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("    ____________\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("   /            \\\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  /              \\\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  |  +--+  +--+  |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" (|  |%% |  |%% |  |)\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("(y|  +--+  +--+  |y)\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__(" (|      oo      |)\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  |  |        |  |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("  \\  +--------+  /\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("   \\____________/\n");


	return 0;

}