#include <stdio.h>
int main(void)

{

	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("#---------------#\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("| x           x |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|   x       x   |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|     x   x     |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|       x       |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|     x   x     |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("|   x       x   |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("| x           x |\n");
	printf__DO_NOT_EDIT_THIS_FILE__CLOSE_THIS_FILE_AND_RUN_THE_PROGRAM_AGAIN_IN_DEBUG_MODE__("#---------------#\n");


	return 0;

}